(ql:quickload '(:str :cl-csv))

(with-open-file (output (merge-pathnames "./http/package.lisp" (uiop:getcwd)) :direction :output :if-exists :supersede :if-does-not-exist :create)
  (with-open-file (file (merge-pathnames "data/http_statuses.csv" (uiop:getcwd)))
    (let ((header '(defpackage #:io.github.cl-sdk.wst.http
                    (:use #:cl))))
      (write header :stream output))
    (write-char #\NEWLINE output)
    (write-char #\NEWLINE output)
    (let ((inpkg '(in-package :io.github.cl-sdk.wst.http)))
      (write inpkg :stream output))
    (write-char #\NEWLINE output)
    (write-char #\NEWLINE output)
    (map nil (lambda (row)
               (destructuring-bind (code message doc link)
                   row
                 (let* ((var-text (str:concat "http-status-" code))
                        (var-name (intern (str:upcase var-text)))
                        (code-var-name (intern (str:upcase (str:concat "+" var-text "+"))))
                        (var-code `(defvar ,code-var-name
                                     ,(parse-integer code)))
                        (var `(defvar ,var-name
                                ',(list (parse-integer code)
                                        (string message)
                                        (string doc)
                                        (string link)))))
                   (write var-code :stream output)
                   (write-char #\NEWLINE output)
                   (write-char #\NEWLINE output)
                   (write `(export ',code-var-name) :stream output)
                   (write-char #\NEWLINE output)
                   (write-char #\NEWLINE output)

                   (write var :stream output)
                   (write-char #\NEWLINE output)
                   (write-char #\NEWLINE output)
                   (write `(export ',var-name) :stream output)
                   (write-char #\NEWLINE output)
                   (write-char #\NEWLINE output))))
         (cdr (cl-csv:read-csv file)))))
